version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7-fpm-browsers-legacy
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: composer install -n --prefer-dist
      - run:
          name: "Run tests"
          command: phpdbg -qrr vendor/bin/phpunit --coverage-html build/coverage-report --coverage-clover=coverage.xml
      - store_artifacts:
          path:  build/coverage-report
      - run:
          name: Upload code coverage to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
